# fly.toml app configuration file generated for cinemazarelos on 2024-01-09T03:58:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cinemazarelos"
primary_region = "mad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
